### ISSUE TITLE
Connection properties view

### ISSUE THREAD

**Issue by echoonly** [lutzroeder/netron#1122]
I have a model where the nodes are quite numerous, resulting in very long and overlapping connections between nodes. It has become challenging to distinguish which nodes are connected due to the excessive overlapping. I hope there is a way to select or search for a connection and view its properties, such as the upstream and downstream nodes, in addition to other attributes. These properties can be displayed in a right-side window, similar to how we view node properties.
<img width="729" alt="image" src="https://github.com/lutzroeder/netron/assets/11766632/210c4ab8-3c5f-4f1c-90b7-e903570045db">

**Comment by beru** [comment]
@lutzroeder wouldn't it be good to show node names instead of node types on NodeView items on the ConnectionSideBar? Because there're cases that all the node types of OUTPUTS are the same, and seeing just the same node type doesn't help very much.

And I also would like to go back to NODE PROPERTIES sidebar from CONNECTION PROPERTIES sidebar by pressing Alt + left key.

**Comment by beru** [comment]
@lutzroeder thank you for updating the code in 40abd7fcf28b16f1145e5002f2f9e191f18e6411. Now NodeListView items are expanded when they are born so it's much easier to see the ConnectionSidebar.

Clicking connections to network inputs/outputs raises an exception in view.NodeView.toggle method since this._expander is undefined. Could you do something about it?

```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'innerText')
  at view.NodeView.toggle (D:\projects\netron\source\view.js:2807:28)
    at new view.NodeListView (D:\projects\netron\source\view.js:2837:18)
    at new view.ConnectionSidebar (D:\projects\netron\source\view.js:2866:26)
    at view.View.showConnectionProperties (D:\projects\netron\source\view.js:1016:39)
    at view.Value.activate (D:\projects\netron\source\view.js:2074:27)
    at view.Graph.activate (D:\projects\netron\source\view.js:1761:21)
    at D:\projects\netron\source\view.js:999:47
    at view.NodeSidebar.emit (D:\projects\netron\source\view.js:2214:17)
    at D:\projects\netron\source\view.js:2338:56
    at view.ArgumentView.emit (D:\projects\netron\source\view.js:2214:17)
```
