### ISSUE TITLE
Python 3.12.2 Support - RuntimeError

### ISSUE THREAD

**Issue by LanluZ** [lutzroeder/netron#1259]
When using netron.start(save_onnx_model_path) produced the following error message

Using Python 3.11.* did not create the problem.

```
Exception occurred during processing of request from ('127.0.0.1', 3406)
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\pytorchCuda124\Lib\socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "D:\ProgramData\anaconda3\envs\pytorchCuda124\Lib\socketserver.py", line 706, in process_request
    t.start()
  File "D:\ProgramData\anaconda3\envs\pytorchCuda124\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
```

**Comment by lutzroeder** [comment]
```
~: python
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
>>> import netron
>>> netron.start('test.onnx')
Serving 'test.onnx' at http://localhost:8080
('localhost', 8080)
>>> 
```

**Comment by LanluZ** [comment]
Thank you!

And I'm srroy, I wasn't able to notice before that debugging and using it alone doesn't produce this error
After retrying I got code that reproduces the Issue in Python 3.12.2.

Otherwise, my environment is as follows.

```
torch==2.2.2
torchaudio==2.2.2
torchvision==0.17.2
netron==7.5.7
python==3.12.2
cuda 12.1
```


```python
import netron
import torch
import torch.onnx
import torch.nn as nn


def main():
    # Load model
    model = LSTM(5, 200, 2, 4)
    inputs = torch.randn(1, 5)
    torch.onnx.export(model, inputs, "model.onnx")
    netron.start("model.onnx")


class LSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(LSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=False)
        self.classifier = nn.Sequential(nn.Linear(hidden_size, output_size))

    def forward(self, x):
        x, _ = self.lstm(x, None)
        x = self.classifier(x)
        return x


if __name__ == '__main__':
    main()
```

> ```
> ~: python
> Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
> >>> import netron
> >>> netron.start('test.onnx')
> Serving 'test.onnx' at http://localhost:8080
> ('localhost', 8080)
> >>> 
> ```

**Comment by LanluZ** [comment]
If you run the program directly it produces the issue as shown here.

![image](https://github.com/lutzroeder/netron/assets/41728500/675271c8-049f-4ae1-b961-9a7ed1d46498)

In addition to this, if you breakpoint at the line where netron.start("model.onnx") is located, the issue will not be generated, as follows. Also python 3.11.* does not generate this issue.

![image](https://github.com/lutzroeder/netron/assets/41728500/31388b76-67f7-47ed-9039-64455e862b3b)

**Comment by lutzroeder** [comment]
The program will start the server and exit before the browser finished the load request. Call `netron.wait()` after `netron.start(...)` to prevent this from happening.
