### ISSUE TITLE
error in Ubuntu 18.04

### ISSUE THREAD

**Issue by haifenghan** [lutzroeder/netron#166]
After installing Netron_2.3.3.deb on Ubuntu 18.04, I'll get the following error:

```
Error: Error: ENOENT: no such file or directory, open '/opt/Netron/resources/app-update.yml'
    at /opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:427:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:423:33)
    at Lazy.AppUpdater.configOnDisk (/opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:138:43)
    at Lazy.get value [as value] (/opt/Netron/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:339:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at Application._checkForUpdates (/opt/Netron/resources/app.asar/src/app.js:249:21)
    at new Application (/opt/Netron/resources/app.asar/src/app.js:70:14)
    at Object.<anonymous> (/opt/Netron/resources/app.asar/src/app.js:894:19)
    at Object.<anonymous> (/opt/Netron/resources/app.asar/src/app.js:896:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (/opt/Netron/resources/electron.asar/browser/init.js:189:8)
    at Object.<anonymous> (/opt/Netron/resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
Gtk-Message: 14:18:45.875: GtkDialog mapped without a transient parent. This is discouraged.

```

And it'll get stuck on Ubuntu while it's easy to show graph by chrome brower on Windows.

**Comment by lutzroeder** [comment]
See electron-userland/electron-builder#2364 and electron-userland/electron-builder#1138. 

@haifenghan can you work on fixing the electron-updater issue?

Is the error blocking the app from running? I tried running 2.3.3 on 18.04 and it works fine but I am not seeing the `Gtk-Message`.
