### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by Pinnh** [lutzroeder/netron#232]
when use netron in Ubuntu 16.04 (deb package or python package) issue happens:

Traceback (most recent call last):
  File "/usr/local/bin/netron", line 7, in <module>
    from netron import main
  File "/usr/local/lib/python2.7/dist-packages/netron/__init__.py", line 2, in <module>
    from .server import start
  File "/usr/local/lib/python2.7/dist-packages/netron/server.py", line 114
    class HTTPServerThread(threading.Thread):
        ^
IndentationError: expected an indented block

the problem is in /usr/local/lib/python2.7/dist-packages/netron/server.py line 112

class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    **pass**# add pass

**Comment by lutzroeder** [comment]
Fixed in version `2.9.0`.
