### ISSUE TITLE
Please select an available port instead of using one fixed port (OSError: [Errno 48] Address already in use)

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#389]
Instead of defaulting to port 8080, a better strategy for netron would be to use a random port with a higher value, say in 20,000+ range. Using random port would greatly reduce the likelihood of the error in itself, but you can also add logic to change port when it happens to be used.

```
Traceback (most recent call last):
  File "/usr/local/bin/netron", line 11, in <module>
    load_entry_point('netron==3.6.0', 'console_scripts', 'netron')()
  File "/usr/local/lib/python3.6/site-packages/netron/__init__.py", line 27, in main
    serve(args.file, None, log=args.log, browse=args.browse, port=args.port, host=args.host)
  File "/usr/local/lib/python3.6/site-packages/netron/server.py", line 204, in serve
    thread = HTTPServerThread(data, file, log, port, host, url)
  File "/usr/local/lib/python3.6/site-packages/netron/server.py", line 121, in __init__
    self.server = ThreadedHTTPServer((host, port), HTTPRequestHandler)
  File "/usr/local/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```

**Comment by lutzroeder** [comment]
`--port` allows specifying a port manually. Please submit a PR to add port allocation and we can from there...
