### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by chandrasekarnarayana** [lutzroeder/netron#972]
Serving 'combination_unet_dense_regression_custom_lossfn_WMRE_metric_MRE_lr_0,003_bs_101_seed_1_eps_5_model.h5' at http://localhost:8080

```
Exception occurred during processing of request from ('127.0.0.1', 47836)
Traceback (most recent call last):
  File "/home/cs/anaconda3/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/cs/anaconda3/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/cs/anaconda3/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/cs/anaconda3/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/cs/anaconda3/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/home/cs/anaconda3/lib/python3.9/site-packages/netron/server.py", line 103, in do_GET
    self._write(status_code, content_type, content)
  File "/home/cs/anaconda3/lib/python3.9/site-packages/netron/server.py", line 114, in _write
    self.wfile.write(str(status_code))
  File "/home/cs/anaconda3/lib/python3.9/socketserver.py", line 826, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by chandrasekarnarayana** [comment]
![Screenshot from 2022-09-23 05-38-18](https://user-images.githubusercontent.com/68073064/191887928-e8a2eaf0-5416-4fd0-aad5-70cdee603ccd.png)
![image](https://user-images.githubusercontent.com/68073064/191888201-fd872b59-7677-409c-b4b7-fd68c2a10f9f.png)

**Comment by Victordongy** [comment]
Hi I encountered the same problem for .onnx file here. Wondering what might cause this and how to fix it ?
